Repository nf-core/eager, pull requests merged in 2019-11, with the labels that each got.

#262 Adding example schematic images to output docs
  docs/images/output/adapter_removal/adapter_removal_discarded_reads.png
  docs/images/output/adapter_removal/adapter_removal_length_distribution.png
  docs/images/output/damageprofiler/damageprofiler.png
  docs/images/output/fastqc/adapter_content.png
  docs/images/output/fastqc/per_base_n_content.png
  docs/images/output/fastqc/per_base_sequence_content.png
  docs/images/output/fastqc/per_sequence_GC_content.png
  docs/images/output/fastqc/per_sequence_quality_score.png
  docs/images/output/fastqc/sequence_counts.png
  docs/images/output/fastqc/sequence_duplication_level.png
  docs/images/output/fastqc/sequencing_quality_histogram.png
  docs/images/output/samtools_flagstat/samtools_flagstat.png
  docs/output.md
Labels: 2.1.0, WIP

#279 Attempt 2 for nf-core tower functionality (once again)
  .travis.yml
  conf/test.config
  conf/test_bam.config
  conf/test_fna.config
  conf/test_humanbam.config
  conf/test_pretrim.config
Labels: WIP

#280 Travis to GitHub Actions Migration
  .github/workflows/nf-core_eager.yml
Labels: WIP

#281 Reviving github actions testing
  .github/workflows/ci-extra.yml
  .github/workflows/ci.yml
  .github/workflows/nf-core_eager.yml
  environment.yml
Labels: ready

#282 GitHub actions secrets
  .github/workflows/nf-core_eager.yml
  environment.yml
Labels: enhancement

#283 GitHub actions secrets
  .github/workflows/branch.yml
  .github/workflows/linting.yml
  .github/workflows/nf-core_eager.yml
Labels: enhancement

#275 Nuclear contamination
  bin/print_x_contamination.py
Labels: WIP, small_fix

#285 Pr template fix
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: minor, ready

#287 Hops
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/workflows/nf-core_eager.yml
  .travis.yml
  CHANGELOG.md
  README.md
  conf/base.config
  docs/faq.md
  docs/output.md
  docs/usage.md
  environment.yml
  main.nf
  nextflow.config
Labels: 2.1.0, feature, ready

#289 Moving default params from main.nf to nextflow.config
  docs/code_contribution.md
  docs/usage.md
  main.nf
  nextflow.config
Labels: 2.1.0, WIP

#292 Software versions
  CHANGELOG.md
  bin/scrape_software_versions.py
  docs/code_contribution.md
  environment.yml
  main.nf
Labels: enhancement, minor
