Repository nf-core/eager, pull requests merged in 2020-02, with the labels that each got.

#343 [Merge #342 first] Performance improvement: zcat to cat
  CHANGELOG.md
  main.nf
Labels: minor

#351 Damageprofiler yaxis
  .github/workflows/ci.yml
  CHANGELOG.md
  docs/usage.md
  main.nf
  nextflow.config
Labels: enhancement

#355 Adding Kraken2 metagenomics classifier
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  bin/kraken_parse.py
  bin/merge_kraken_res.py
  conf/test_kraken.config
  docs/output.md
  docs/usage.md
  main.nf
  nextflow.config
Labels: 2.1.0, enhancement, feature

#358 Add endogenous DNA calculation script
  CHANGELOG.md
  assets/multiqc_config.yaml
  bin/endorS.py
  docs/output.md
  main.nf
Labels: enhancement
